# Generated by Django 4.2.13 on 2026-07-22 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainHealthDataIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('socioeconomic_score', models.FloatField()),
                ('environmental_impact_score', models.FloatField()),
                ('overall_index', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=4.9)),
                ('available_for_telemedicine', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, default='https://ui-avatars.com/api/?name=Doc&background=0D8ABC&color=fff', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coverage_details', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('encrypted_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTourismFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('PHC', 'Primary Healthcare Centre'), ('HOSPITAL', 'Specialized Hospital'), ('RESEARCH', 'Medical Research Centre'), ('VR_AR', 'VR/AR Neuro-Rehab Center')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NeurolearnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=150)),
                ('duration_hours', models.IntegerField()),
                ('difficulty', models.CharField(default='Beginner', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuroProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Guest User', max_length=200)),
                ('pathway', models.CharField(default='Patient/User', max_length=100)),
                ('cognitive_goal', models.CharField(default='Memory & Concentration', max_length=100)),
                ('bci_familiarity', models.CharField(default='First Time', max_length=100)),
                ('environment', models.CharField(default='Urban Center', max_length=100)),
                ('subscription_tier', models.CharField(default='Standard Pro', max_length=50)),
                ('web3_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('data_processing_consent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(default='Planned', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicaltourismfacility')),
            ],
        ),
    ]
