# Generated by Django 4.2.13 on 2026-07-22 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_healthwallettransaction_user_medicalitinerary_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('modality', models.CharField(choices=[('telemedicine', 'Telemedicine'), ('in_person', 'In-Person')], default='telemedicine', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('sync_baseline', models.BooleanField(default=True)),
                ('sync_emr', models.BooleanField(default=True)),
                ('sync_pharm', models.BooleanField(default=False)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(default='requested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinician')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicaltourismfacility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(max_length=100)),
                ('granted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='core.appointment')),
            ],
        ),
    ]
