# Generated by Django 4.2.13 on 2026-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userinsurancesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalitinerary',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
