# Generated by Django 4.2.13 on 2026-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resourceitem_neuroprofile_account_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='file_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='neuroprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
