from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('onboarding/', views.onboarding, name='onboarding'),
    path('myspace/', views.myspace, name='myspace'),
    path('clinical-care/', views.clinical_care, name='clinical_care'),
    path('medical-tourism/', views.medical_tourism, name='medical_tourism'),
    path('medical-tourism/create/', views.medical_itinerary_create, name='medical_itinerary_create'),
    path('insurance/', views.insurance, name='insurance'),
    path('insurance/subscribe/', views.insurance_subscribe, name='insurance_subscribe'),
    path('appointment/', views.appointment, name='appointment'),
    path('wellness/', views.wellness, name='wellness'),
    path('wellness/sync/', views.wellness_sync, name='wellness_sync'),
    path('wellness/mental-health/', views.mental_health_screening, name='mental_health_screening'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/mark-read/', views.notifications_mark_read, name='notifications_mark_read'),
    path('select-plan/', views.select_plan, name='select_plan'),
    path('messages/', views.messages, name='messages'),
    path('messages/send/', views.messages_send, name='messages_send'),
    path('health-wallet/', views.health_wallet, name='health_wallet'),
    path('history/', views.history, name='history'),
    path('history/report/<int:report_id>/', views.history_report_detail, name='history_report_detail'),
    path('history/report/<int:report_id>/download/', views.history_download_report, name='history_download_report'),
    path('history/report/<int:report_id>/share/', views.history_share_report, name='history_share_report'),
    path('nbhdi-resources/', views.nbhdi_resources, name='nbhdi_resources'),
    path('nbhdi-resources/<int:resource_id>/', views.nbhdi_resource_action, name='nbhdi_resource_action'),
    path('neurolearn/', views.neurolearn, name='neurolearn'),
    path('neurolearn/start/<int:course_id>/', views.neurolearn_start_module, name='neurolearn_start_module'),
    path('greenspace/', views.greenspace, name='greenspace'),
    path('greenspace/join/', views.greenspace_join, name='greenspace_join'),
    path('profile/', views.profile, name='profile'),
    path('profile/lock/', views.profile_lock, name='profile_lock'),
    path('feature-hints/mark-seen/', views.feature_hint_mark_seen, name='feature_hint_mark_seen'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]
